server:
  port: 8080
  servlet:
    context-path: "/api"
spring:
  jpa:
    hibernate.ddl-auto: create
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  h2:
    console:
      enabled: true
      path: /h2-console
